'use client';
import './library.css';
import {useEffect,useState,useCallback,useRef} from 'react';
import {Disc3,Heart,ListMusic,Search,Sparkles,Moon,Sun,SkipBack,SkipForward,Play,Pause,Volume2,Loader2,Youtube,Plus,Link as LinkIcon,Menu,ChevronLeft,Trash2,Home as HomeIcon,Shuffle,Repeat,MoreVertical,ArrowUp,ArrowDown,X} from 'lucide-react';
import ReliableYouTubePlayer,{PlayerHandle} from '@/components/ReliableYouTubePlayer';
import {searchYouTube,YouTubeTrack,extractYouTubeId} from '@/lib/youtube';
const palettes=[['#ff2fb3','#ffd400','#06f'],['#ff5a00','#ffdf00','#9d4edd'],['#b7ff00','#ff3cac','#00d4ff'],['#ff7b00','#ff2d55','#6930c3'],['#00e5ff','#ffea00','#ff3cac']];
type NamedPlaylist={id:string;name:string;songs:YouTubeTrack[]};
export default function Home(){
 const player=useRef<PlayerHandle>(null);const[tracks,setTracks]=useState<YouTubeTrack[]>([]),[selected,setSelected]=useState(0),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[dark,setDark]=useState(true),[volume,setVolume]=useState(72),[dragging,setDragging]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<YouTubeTrack[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[liked,setLiked]=useState<YouTubeTrack[]>([]),[playlists,setPlaylists]=useState<NamedPlaylist[]>([]),[screen,setScreen]=useState('home'),[collapsed,setCollapsed]=useState(false),[queue,setQueue]=useState<YouTubeTrack[]>([]),[repeat,setRepeat]=useState(false),[menu,setMenu]=useState<string|null>(null),[newName,setNewName]=useState('');
 useEffect(()=>{try{setLiked(JSON.parse(localStorage.getItem('y2k_liked')||'[]'));setPlaylists(JSON.parse(localStorage.getItem('y2k_playlists')||'[]'))}catch{}},[]);useEffect(()=>localStorage.setItem('y2k_liked',JSON.stringify(liked)),[liked]);useEffect(()=>localStorage.setItem('y2k_playlists',JSON.stringify(playlists)),[playlists]);
 const track=tracks[selected],palette=palettes[selected%5];
 const playTrack=(t:YouTubeTrack)=>{setTracks(x=>{const i=x.findIndex(y=>y.id===t.id);if(i>=0){setSelected(i);return x}const n=[...x,t];setSelected(n.length-1);return n});setTime(0);setDuration(0);setPlaying(true);setScreen('home')};
 const addQueue=(t:YouTubeTrack)=>setQueue(q=>q.some(x=>x.id===t.id)?q:[...q,t]);
 const next=useCallback(()=>{if(queue.length){const[t,...rest]=queue;setQueue(rest);playTrack(t);return}if(!tracks.length)return;if(repeat){player.current?.seek(0);player.current?.play();return}setSelected(i=>(i+1)%tracks.length);setTime(0);setDuration(0);setPlaying(true)},[queue,tracks,repeat]);
 const previous=()=>{if(!tracks.length)return;setSelected(i=>(i-1+tracks.length)%tracks.length);setTime(0);setDuration(0);setPlaying(true)};
 const toggleLike=()=>{if(!track)return;setLiked(p=>p.some(x=>x.id===track.id)?p.filter(x=>x.id!==track.id):[...p,track])};
 const search=async()=>{if(!query.trim())return;setLoading(true);setError('');try{setResults(await searchYouTube(query))}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const addLink=()=>{const id=extractYouTubeId(link);if(!id){setError('Invalid YouTube link.');return}const t={id,title:'YouTube video',artist:'Pasted video',channel:'YouTube',thumbnail:`https://i.ytimg.com/vi/${id}/hqdefault.jpg`};setPlaylists(p=>p);setQueue(q=>q);playTrack(t);setLink('');setError('')};
 const[link,setLink]=useState('');const onTime=useCallback((c:number,d:number)=>{setTime(c);setDuration(d)},[]);const seek=(v:number)=>{setTime(v);player.current?.seek(v)};
 const needleDown=(e:React.PointerEvent<HTMLDivElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);setDragging(true)};const needleMove=(e:React.PointerEvent<HTMLDivElement>)=>{if(!dragging)return;const r=e.currentTarget.parentElement?.getBoundingClientRect();if(r){const on=Math.hypot(e.clientX-(r.left+r.width/2),e.clientY-(r.top+r.height/2))<r.width*.37;on?player.current?.play():player.current?.pause();setPlaying(on)}};const needleUp=()=>setDragging(false);
 const createPlaylist=()=>{const name=newName.trim();if(!name)return;setPlaylists(p=>[...p,{id:crypto.randomUUID(),name,songs:[]}]);setNewName('')};
 const addToPlaylist=(pid:string,t:YouTubeTrack)=>setPlaylists(p=>p.map(x=>x.id===pid&& !x.songs.some(s=>s.id===t.id)?{...x,songs:[...x.songs,t]}:x));
 const playAll=(songs:YouTubeTrack[])=>{if(!songs.length)return;setTracks(songs);setSelected(0);setQueue(songs.slice(1));setTime(0);setDuration(0);setPlaying(true);setScreen('home')};
 const shuffleAll=(songs:YouTubeTrack[])=>{const a=[...songs].sort(()=>Math.random()-.5);playAll(a)};
 const moveSong=(pid:string,i:number,dir:number)=>setPlaylists(ps=>ps.map(p=>{if(p.id!==pid)return p;const n=i+dir;if(n<0||n>=p.songs.length)return p;const songs=[...p.songs];[songs[i],songs[n]]=[songs[n],songs[i]];return{...p,songs}}));
 const title={home:'MY MUSIC',liked:'LIKED SONGS',playlists:'PLAYLISTS',search:'SEARCH YOUTUBE'}[screen]||'PLAYLIST';
 return <main className={`shell ${dark?'dark':'light'} ${collapsed?'nav-collapsed':''}`} style={{'--a':palette?.[0]||'#ff2fb3','--b':palette?.[1]||'#ffd400','--c':palette?.[2]||'#06f'} as React.CSSProperties}><div className="window"><header className="topbar"><button className="menu-toggle icon-btn" onClick={()=>setCollapsed(x=>!x)}>{collapsed?<Menu/>:<ChevronLeft/>}</button><div className="logo"><Disc3/>Y2K <span>PLAYER</span></div><div className="top-actions"><div className="status"><i className="status-dot"/> YOUTUBE READY</div><div className="clock">{new Date().toLocaleTimeString([],{hour12:false})}</div><button className="icon-btn" onClick={()=>setDark(x=>!x)}>{dark?<Sun/>:<Moon/>}</button></div></header><section className="body"><aside className="sidebar"><div className="side-label">MENU</div><nav className="nav"><button className={screen==='home'?'active':''} onClick={()=>setScreen('home')}><HomeIcon/><span>HOME</span></button><button className={screen==='liked'?'active':''} onClick={()=>setScreen('liked')}><Heart/><span>LIKED SONGS</span></button><button className={screen==='playlists'?'active':''} onClick={()=>setScreen('playlists')}><ListMusic/><span>PLAYLISTS</span></button></nav><div className="side-label">DISCOVER</div><nav className="nav"><button className={screen==='search'?'active':''} onClick={()=>setScreen('search')}><Search/><span>SEARCH YOUTUBE</span></button><button onClick={()=>setScreen('home')}><Sparkles/><span>BROWSE</span></button></nav><div className="system"><div className="sys-title"><Youtube/> YOUTUBE / ONLINE</div><p>Y2KP-03 // REV 7.0</p><p>LOCAL LIBRARY ENGINE</p><p>NO ACCOUNT REQUIRED</p><div className="sys-bars"><b/><b/><b/><b/><b/></div></div></aside>
 <section className="center"><div className="center-head"><div><div className="kicker">YOUTUBE AUDIO / {screen.toUpperCase()}</div><h1>{title}</h1></div><div className="badge">{loading?<><Loader2/> SEARCHING</>:playing?'● PLAYING':'Ⅱ PAUSED'}</div></div>{error&&<button className="error-bar" onClick={()=>setError('')}>{error} ×</button>}
 {screen==='home'&&<><div className="turntable"><div className="orbit orbit1"/><div className="orbit orbit2"/><div className={`needle ${playing?'on-record':''} ${dragging?'dragging':''}`} onPointerDown={needleDown} onPointerMove={needleMove} onPointerUp={needleUp}><div className="needle-base"/><div className="needle-arm"/><div className="needle-head"/></div>{track?<div className="vinyl" style={{animationPlayState:playing?'running':'paused'}}><div className="record-shine"/><img className="vinyl-cover" src={track.thumbnail} alt=""/><div className="label" style={{background:`linear-gradient(145deg,${palette[0]},${palette[2]})`}}><div className="label-inner"><strong>{track.title}</strong><small>{track.artist} / SIDE A</small></div></div><div className="spindle"/></div>:<div className="empty-record"><Disc3/><strong>NO TRACK LOADED</strong><small>SEARCH YOUTUBE OR PASTE A LINK</small></div>}<div className="deck-caption"><span>◉ 12&quot; DIGITAL VINYL</span><span>RPM 33⅓</span><span>{dragging?'DRAGGING':playing?'NEEDLE ON':'NEEDLE UP'}</span></div></div><div className="collection"><div className="collection-head"><span>QUEUE</span><b>{queue.length} UP NEXT</b></div><div className="collection-row">{queue.slice(0,5).map((t,i)=><button className="collection-card" key={t.id+i} onClick={()=>{setQueue(q=>q.filter(x=>x.id!==t.id));playTrack(t)}}><div className="collection-art"><img src={t.thumbnail} alt=""/></div><div><strong>{t.title}</strong><small>{t.artist}</small></div></button>)}{!queue.length&&<div className="empty">Queue is empty. Use Add to Queue from Search or Playlists.</div>}</div></div></>}
 {screen==='liked'&&<SongList songs={liked} onPlay={playTrack} onQueue={addQueue} liked onLike={toggleLike}/>} {screen==='playlists'&&<div className="library-screen"><div className="create-row"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="NEW PLAYLIST NAME..." onKeyDown={e=>e.key==='Enter'&&createPlaylist()}/><button onClick={createPlaylist}><Plus/> CREATE</button></div>{playlists.map(p=><div className="playlist-block" key={p.id}><div className="playlist-head"><div><b>{p.name}</b><small>{p.songs.length} SONGS</small></div><div><button onClick={()=>playAll(p.songs)}><Play/> PLAY ALL</button><button onClick={()=>shuffleAll(p.songs)}><Shuffle/> SHUFFLE</button><button onClick={()=>setPlaylists(ps=>ps.filter(x=>x.id!==p.id))}><Trash2/></button></div></div>{p.songs.map((t,i)=><div className="playlist-song" key={t.id}><span>{String(i+1).padStart(2,'0')}</span><img src={t.thumbnail} alt=""/><div><b>{t.title}</b><small>{t.artist}</small></div><button onClick={()=>playTrack(t)}><Play/></button><button onClick={()=>addQueue(t)}><Plus/></button><button onClick={()=>moveSong(p.id,i,-1)}><ArrowUp/></button><button onClick={()=>moveSong(p.id,i,1)}><ArrowDown/></button></div>)}</div>)}{!playlists.length&&<div className="empty-library"><ListMusic/><strong>NO PLAYLISTS</strong><small>Create one above, then add songs from Search.</small></div>}</div>}
 {screen==='search'&&<div className="full-search"><div className="search-zone"><div className="search-head"><Search/><input className="search-input" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="SEARCH YOUTUBE..."/><button onClick={search}>GO</button></div><div className="link-head"><LinkIcon/><input value={link} onChange={e=>setLink(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addLink()} placeholder="PASTE YOUTUBE LINK..."/><button onClick={addLink}><Plus/> PLAY</button></div>{results.map(t=><div className="result" key={t.id}><img src={t.thumbnail} alt=""/><div><b>{t.title}</b><small>{t.artist}</small></div><button onClick={()=>addQueue(t)} title="Add to queue"><ListMusic/></button><button onClick={()=>setMenu(menu===t.id?null:t.id)}><MoreVertical/></button><button onClick={()=>playTrack(t)}><Play/></button>{menu===t.id&&<div className="track-menu"><button onClick={()=>{setLiked(p=>p.some(x=>x.id===t.id)?p.filter(x=>x.id!==t.id):[...p,t]);setMenu(null)}}><Heart/> LIKE</button>{playlists.map(p=><button key={p.id} onClick={()=>{addToPlaylist(p.id,t);setMenu(null)}}>+ {p.name}</button>)}{!playlists.length&&<span>Create a playlist first</span>}</div>}</div>)}</div></div>}
 </section><aside className="now"><div className="panel-title"><span>NOW PLAYING</span><span>{track?'● '+String(selected+1).padStart(2,'0'):'—'}</span></div><div className="cover">{track?.thumbnail&&<img src={track.thumbnail} alt="Album artwork"/>}<div className="cover-grid"/><div className="cover-star">★</div></div><div className="track-name">{track?.title||'NOTHING PLAYING'}</div><div className="artist">{track?.artist?.toUpperCase()||'ADD A YOUTUBE VIDEO'}</div>{track&&<><button className={`like-button ${liked.some(x=>x.id===track.id)?'liked':''}`} onClick={toggleLike}><Heart/> {liked.some(x=>x.id===track.id)?'LIKED':'LIKE SONG'}</button><div className="progress"><input type="range" min="0" max={Math.max(duration,1)} step="0.1" value={Math.min(time,duration||1)} onChange={e=>seek(+e.target.value)}/><div className="times"><span>{fmt(time)}</span><span>{duration?fmt(duration):'--:--'}</span></div></div><div className="controls"><button className="control" onClick={previous}><SkipBack/></button><button className="control main" onClick={()=>playing?player.current?.pause():player.current?.play()}>{playing?<Pause/>:<Play/>}</button><button className="control" onClick={next}><SkipForward/></button></div><div className="play-modes"><button className={repeat?'active':''} onClick={()=>setRepeat(x=>!x)}><Repeat/></button><button onClick={()=>shuffleAll(tracks)}><Shuffle/></button></div><div className="volume"><Volume2/><input type="range" min="0" max="100" value={volume} onChange={e=>setVolume(+e.target.value)}/><span>{volume}%</span></div></>}</aside></section><footer className="footer"><div className="footer-label">QUEUE</div>{queue.slice(0,8).map((t,i)=><button className="track-card" onClick={()=>{setQueue(q=>q.filter(x=>x.id!==t.id));playTrack(t)}} key={t.id+i}><div className="mini"><img src={t.thumbnail} alt=""/></div><div><b>{String(i+1).padStart(2,'0')} / {t.title}</b><span>{t.artist}</span></div><X/></button>)}</footer><div className="youtube-hidden"><ReliableYouTubePlayer ref={player} videoId={track?.id||''} volume={volume} onStateChange={setPlaying} onTime={onTime} onEnded={next}/></div></div></main>}
function fmt(s:number){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`}
function SongList({songs,onPlay,onQueue,liked,onLike}:{songs:YouTubeTrack[];onPlay:(t:YouTubeTrack)=>void;onQueue:(t:YouTubeTrack)=>void;liked?:boolean;onLike?:()=>void}){return <div className="library-screen"><div className="library-toolbar"><span>{songs.length} SONGS</span><span>LOCAL</span></div>{songs.length?<div className="library-grid">{songs.map((t,i)=><article className="library-item" key={t.id+i}><img src={t.thumbnail} alt=""/><div className="library-info"><b>{t.title}</b><small>{t.artist}</small></div><button onClick={()=>onPlay(t)}><Play/></button><button onClick={()=>onQueue(t)}><ListMusic/></button></article>)}</div>:<div className="empty-library"><Heart/><strong>NO LIKED SONGS</strong><small>Like songs from Search to see them here.</small></div>}</div>}
