'use client';
import {useEffect,useRef,useImperativeHandle,forwardRef} from 'react';
declare global{interface Window{YT:any;onYouTubeIframeAPIReady?:()=>void}}
export type PlayerHandle={play:()=>void;pause:()=>void;seek:(seconds:number)=>void;loadAndPlay:(videoId:string,startAt?:number)=>void};
type Props={videoId:string;volume:number;onStateChange:(playing:boolean)=>void;onTime:(current:number,duration:number)=>void;onEnded:()=>void;onError?:(code:number)=>void};
const ReliableYouTubePlayer=forwardRef<PlayerHandle,Props>(function ReliableYouTubePlayer({videoId,volume,onStateChange,onTime,onEnded,onError},ref){
 const mount=useRef<HTMLDivElement>(null),player=useRef<any>(null),ready=useRef(false),timer=useRef<ReturnType<typeof setInterval>|null>(null),pending=useRef<{id:string;startAt:number}|null>(null);
 const safe=(fn:(p:any)=>void)=>{const p=player.current;if(ready.current&&p&&typeof fn==='function')fn(p)};
 useImperativeHandle(ref,()=>({play:()=>safe(p=>p.playVideo()),pause:()=>safe(p=>p.pauseVideo()),seek:s=>safe(p=>p.seekTo(s,true)),loadAndPlay:(id,startAt=0)=>{pending.current={id,startAt};if(ready.current&&player.current){player.current.loadVideoById({videoId:id,startSeconds:startAt});player.current.playVideo()}}}),[]);
 useEffect(()=>{if(!videoId)return;pending.current={id:videoId,startAt:0};if(ready.current&&player.current&&typeof player.current.loadVideoById==='function'){player.current.loadVideoById(videoId);player.current.playVideo()}},[videoId]);
 useEffect(()=>{if(!mount.current)return;let dead=false;const create=()=>{if(dead||!window.YT?.Player||!mount.current)return;const p=new window.YT.Player(mount.current,{width:'1',height:'1',videoId:'',origin:window.location.origin,playerVars:{autoplay:0,controls:0,rel:0,playsinline:1,origin:window.location.origin},events:{onReady:(e:any)=>{if(dead)return;ready.current=true;e.target.setVolume(volume);if(pending.current){const x=pending.current;pending.current=null;e.target.loadVideoById({videoId:x.id,startSeconds:x.startAt});e.target.playVideo()}},onStateChange:(e:any)=>{const state=e.data;onStateChange(state===window.YT.PlayerState.PLAYING);if(state===window.YT.PlayerState.ENDED)onEnded()},onError:(e:any)=>onError?.(e.data)}});player.current=p};if(window.YT?.Player)create();else{const old=document.querySelector('script[data-youtube-api]');if(!old){const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';s.dataset.youtubeApi='true';document.body.appendChild(s)}const previous=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{previous?.();create()}}return()=>{dead=true;ready.current=false;if(timer.current)clearInterval(timer.current);player.current?.destroy?.();player.current=null}},[]);
 useEffect(()=>safe(p=>p.setVolume(volume)),[volume]);
 useEffect(()=>{if(timer.current)clearInterval(timer.current);timer.current=setInterval(()=>safe(p=>onTime(p.getCurrentTime?.()||0,p.getDuration?.()||0)),400);return()=>{if(timer.current)clearInterval(timer.current)}},[onTime]);
 return <div className="youtube-hidden-player"><div ref={mount}/></div>;
});export default ReliableYouTubePlayer;
